package gorm

import (
	"fast-admin-service/global"
	"fast-admin-service/model"
	"fast-admin-service/pkg/setting"
	"fmt"
	"go.uber.org/zap"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"time"
)

func Setup() {
	//	构造连接池链接
	dsn := fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=True&loc=Local",
		setting.DataBaseOptions.User,
		setting.DataBaseOptions.Password,
		setting.DataBaseOptions.Host,
		setting.DataBaseOptions.Db,
	)
	var err error
	mysqlConfig := mysql.Config{
		DSN:                       dsn,   // DSN data source name
		DefaultStringSize:         191,   // string 类型字段的默认长度
		DisableDatetimePrecision:  true,  // 禁用 datetime 精度，MySQL 5.6 之前的数据库不支持
		DontSupportRenameIndex:    true,  // 重命名索引时采用删除并新建的方式，MySQL 5.7 之前的数据库和 MariaDB 不支持重命名索引
		DontSupportRenameColumn:   true,  // 用 `change` 重命名列，MySQL 8 之前的数据库和 MariaDB 不支持重命名列
		SkipInitializeWithVersion: false, // 根据版本自动配置
	}
	global.GLOBAL_DB, err = gorm.Open(mysql.New(mysqlConfig), &gorm.Config{})
	global.GLOBAL_DB.Logger.LogMode(4)
	if err != nil {
		zap.L().Error("The database connection failed may be due to a timeout")
		return
	}
	sqlDB, err := global.GLOBAL_DB.DB()
	// SetMaxIdleConns 设置空闲连接池中连接的最大数量
	sqlDB.SetMaxIdleConns(10)
	// SetMaxOpenConns 设置打开数据库连接的最大数量。
	sqlDB.SetMaxOpenConns(100)
	// SetConnMaxLifetime 设置了连接可复用的最大时间。
	sqlDB.SetConnMaxLifetime(time.Hour)
	// 数据库迁移
	initDataBase()
	// 图标数据创建
	//InitSystemIcons()
	global.ZAP_LOG.Info("The database connection pool is initialized successfully")
}

// initDataBase 表迁移
func initDataBase() {
	var err error
	err = global.GLOBAL_DB.AutoMigrate(
		&model.SysUser{},
		&model.SysRole{},
		&model.SysBaseMenu{},
		&model.SysIcon{},
	)

	if err != nil {
		zap.S().Error("automiGrate error...")
		return
	}
}

// InitSystemIcons 系统图标数据迁移
func InitSystemIcons() {
	icons := []string{
		"StepBackwardOutlined",
		"StepForwardOutlined",
		"FastBackwardOutlined",
		"FastForwardOutlined",
		"ShrinkOutlined",
		"ArrowsAltOutlined",
		"DownOutlined",
		"UpOutlined",
		"LeftOutlined",
		"RightOutlined",
		"CaretUpOutlined",
		"CaretDownOutlined",
		"CaretLeftOutlined",
		"CaretRightOutlined",
		"UpCircleOutlined",
		"DownCircleOutlined",
		"LeftCircleOutlined",
		"RightCircleOutlined",
		"DoubleRightOutlined",
		"DoubleLeftOutlined",
		"VerticalLeftOutlined",
		"VerticalRightOutlined",
		"VerticalAlignTopOutlined",
		"VerticalAlignMiddleOutlined",
		"VerticalAlignBottomOutlined",
		"ForwardOutlined",
		"BackwardOutlined",
		"RollbackOutlined",
		"EnterOutlined",
		"RetweetOutlined",
		"SwapOutlined",
		"SwapLeftOutlined",
		"SwapRightOutlined",
		"ArrowUpOutlined",
		"ArrowDownOutlined",
		"ArrowLeftOutlined",
		"ArrowRightOutlined",
		"PlayCircleOutlined",
		"UpSquareOutlined",
		"DownSquareOutlined",
		"LeftSquareOutlined",
		"RightSquareOutlined",
		"LoginOutlined",
		"LogoutOutlined",
		"MenuFoldOutlined",
		"MenuUnfoldOutlined",
		"BorderBottomOutlined",
		"BorderHorizontalOutlined",
		"BorderInnerOutlined",
		"BorderOuterOutlined",
		"BorderLeftOutlined",
		"BorderRightOutlined",
		"BorderTopOutlined",
		"BorderVerticleOutlined",
		"PicCenterOutlined",
		"PicLeftOutlined",
		"PicRightOutlined",
		"RadiusBottomleftOutlined",
		"RadiusBottomrightOutlined",
		"RadiusUpleftOutlined",
		"RadiusUprightOutlined",
		"FullscreenOutlined",
		"FullscreenExitOutlined",
		"AccountBookOutlined",
		"AimOutlined",
		"AlertOutlined",
		"ApartmentOutlined",
		"ApiOutlined",
		"AppstoreAddOutlined",
		"AppstoreOutlined",
		"AudioOutlined",
		"AudioMutedOutlined",
		"AuditOutlined",
		"BankOutlined",
		"BarcodeOutlined",
		"BarsOutlined",
		"BellOutlined",
		"BlockOutlined",
		"BookOutlined",
		"BorderOutlined",
		"BorderlessTableOutlined",
		"BranchesOutlined",
		"BugOutlined",
		"BuildOutlined",
		"BulbOutlined",
		"CalculatorOutlined",
		"CalendarOutlined",
		"CameraOutlined",
		"CarOutlined",
		"CarryOutOutlined",
		"CiCircleOutlined",
		"CiOutlined", "ClearOutlined",
		"CloudDownloadOutlined",
		"CloudOutlined",
		"CloudServerOutlined",
		"CloudSyncOutlined",
		"CloudUploadOutlined",
		"ClusterOutlined",
		"CodeOutlined",
		"CoffeeOutlined",
		"CommentOutlined",
		"CompassOutlined",
		"CompressOutlined",
		"ConsoleSqlOutlined",
		"ContactsOutlined",
		"ContainerOutlined",
		"ControlOutlined",
		"CopyrightCircleOutlined",
		"CopyrightOutlined",
		"CreditCardOutlined",
		"CrownOutlined",
		"CustomerServiceOutlined",
		"DashboardOutlined",
		"DatabaseOutlined",
		"DeleteColumnOutlined",
		"DeleteRowOutlined",
		"DeliveredProcedureOutlined",
		"DeploymentUnitOutlined",
		"DesktopOutlined",
		"DingtalkOutlined",
		"DisconnectOutlined",
		"DislikeOutlined",
		"DollarCircleOutlined",
		"DollarOutlined",
		"DownloadOutlined",
		"EllipsisOutlined",
		"EnvironmentOutlined",
		"EuroCircleOutlined",
		"EuroOutlined",
		"ExceptionOutlined",
		"ExpandAltOutlined",
		"ExpandOutlined",
		"ExperimentOutlined",
		"ExportOutlined",
		"EyeOutlined",
		"EyeInvisibleOutlined",
		"FieldBinaryOutlined",
		"FieldNumberOutlined",
		"FieldStringOutlined",
		"FieldTimeOutlined",
		"FileAddOutlined",
		"FileDoneOutlined",
		"FileExcelOutlined",
		"FileExclamationOutlined",
		"FileOutlined",
		"FileGifOutlined",
		"FileImageOutlined",
		"FileJpgOutlined",
		"FileMarkdownOutlined",
		"FilePdfOutlined",
		"FilePptOutlined",
		"FileProtectOutlined",
		"FileSearchOutlined",
		"FileSyncOutlined",
		"FileTextOutlined",
		"FileUnknownOutlined",
		"FileWordOutlined",
		"FileZipOutlined",
		"FilterOutlined",
		"FireOutlined", "FlagOutlined",
		"FolderAddOutlined",
		"FolderOutlined",
		"FolderOpenOutlined",
		"FolderViewOutlined",
		"ForkOutlined",
		"FormatPainterOutlined",
		"FrownOutlined",
		"FunctionOutlined",
		"FundProjectionScreenOutlined",
		"FundViewOutlined",
		"FunnelPlotOutlined",
		"GatewayOutlined",
		"GifOutlined",
		"GiftOutlined",
		"GlobalOutlined",
		"GoldOutlined",
		"GroupOutlined",
		"HddOutlined",
		"HeartOutlined",
		"HistoryOutlined",
		"HomeOutlined",
		"HourglassOutlined",
		"IdcardOutlined",
		"ImportOutlined",
		"InboxOutlined",
		"InsertRowAboveOutlined",
		"InsertRowBelowOutlined",
		"InsertRowLeftOutlined",
		"InsertRowRightOutlined",
		"InsuranceOutlined",
		"InteractionOutlined",
		"KeyOutlined",
		"LaptopOutlined",
		"LayoutOutlined",
		"LikeOutlined",
		"LineOutlined",
		"LinkOutlined",
		"Loading3QuartersOutlined",
		"LoadingOutlined",
		"LockOutlined",
		"MacCommandOutlined",
		"MailOutlined",
		"ManOutlined", "MedicineBoxOutlined",
		"MehOutlined", "MenuOutlined",
		"MergeCellsOutlined",
		"MessageOutlined",
		"MobileOutlined",
		"MoneyCollectOutlined",
		"MonitorOutlined",
		"MoreOutlined",
		"NodeCollapseOutlined",
		"NodeExpandOutlined",
		"NodeIndexOutlined",
		"NotificationOutlined",
		"NumberOutlined",
		"OneToOneOutlined",
		"PaperClipOutlined",
		"PartitionOutlined",
		"PayCircleOutlined",
		"PercentageOutlined",
		"PhoneOutlined",
		"PictureOutlined",
		"PlaySquareOutlined",
		"PoundCircleOutlined",
		"PoundOutlined",
		"PoweroffOutlined",
		"PrinterOutlined",
		"ProfileOutlined",
		"ProjectOutlined",
		"PropertySafetyOutlined",
		"PullRequestOutlined",
		"PushpinOutlined",
		"QrcodeOutlined",
		"ReadOutlined",
		"ReconciliationOutlined",
		"RedEnvelopeOutlined",
		"ReloadOutlined",
		"RestOutlined",
		"RobotOutlined",
		"RocketOutlined",
		"RotateLeftOutlined",
		"RotateRightOutlined",
		"SafetyCertificateOutlined",
		"SafetyOutlined",
		"SaveOutlined",
		"ScanOutlined",
		"ScheduleOutlined",
		"SearchOutlined",
		"SecurityScanOutlined",
		"SelectOutlined",
		"SendOutlined",
		"SettingOutlined",
		"ShakeOutlined",
		"ShareAltOutlined",
		"ShopOutlined",
		"ShoppingCartOutlined",
		"ShoppingOutlined",
		"SisternodeOutlined",
		"SkinOutlined",
		"SmileOutlined",
		"SolutionOutlined",
		"SoundOutlined",
		"SplitCellsOutlined",
		"StarOutlined",
		"SubnodeOutlined",
		"SwitcherOutlined",
		"SyncOutlined",
		"TableOutlined",
		"TabletOutlined",
		"TagOutlined",
		"TagsOutlined",
		"TeamOutlined",
		"ThunderboltOutlined",
		"ToTopOutlined",
		"ToolOutlined",
		"TrademarkCircleOutlined",
		"TrademarkOutlined",
		"TransactionOutlined",
		"TranslationOutlined",
		"TrophyOutlined",
		"UngroupOutlined",
		"UnlockOutlined",
		"UploadOutlined",
		"UsbOutlined",
		"UserAddOutlined",
		"UserDeleteOutlined",
		"UserOutlined",
		"UserSwitchOutlined",
		"UsergroupAddOutlined",
		"UsergroupDeleteOutlined",
		"VerifiedOutlined",
		"VideoCameraAddOutlined",
		"VideoCameraOutlined",
		"WalletOutlined",
		"WhatsAppOutlined",
		"WifiOutlined",
		"WomanOutlined",
	}
	var sysIcons []model.SysIcon
	for _, v := range icons {
		sysIcons = append(sysIcons, model.SysIcon{IconName: v})
	}
	// 创建数据表
	if err := global.GLOBAL_DB.Model(&model.SysIcon{}).Create(sysIcons).Error; err != nil {
		global.ZAP_LOG.Error("init system icons fail....")
	}
}
